// Configuración generada automáticamente desde .env
window.ENV = {
  "EXPO_PUBLIC_SUPABASE_URL": "https://wpecvlperiberbmsndlg.supabase.co",
  "EXPO_PUBLIC_SUPABASE_ANON_KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwZWN2bHBlcmliZXJibXNuZGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzU0NDksImV4cCI6MjA2NzQxMTQ0OX0.Jx0UjYl1pblxsLXGOLSP5j0gzMyXq4arL_dzxN4YFcs",
  "": "",
  "EXPO_PUBLIC_FIREBASE_API_KEY": "AIzaSyBW7YFauqJBbv6Xm8a1tsDLGVDzF6rXHhI",
  "EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN": "taxi-zkt-7f276.firebaseapp.com",
  "EXPO_PUBLIC_FIREBASE_PROJECT_ID": "taxi-zkt-7f276",
  "EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET": "taxi-zkt-7f276.appspot.com",
  "EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID": "570692523770",
  "EXPO_PUBLIC_FIREBASE_APP_ID": "1:570692523770:android:26e5ad5e0c0ded43331b43"
};
